files:
  - source: /locale/en/
    translation: /locale/%two_letters_code%/locale.cfg
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        es-ES: es-ES
    type: ini
    dest: /locale.ini
